export interface StaticProduct {
  id: string
  slug: string
  title: string
  description: string
  price: number
  images: string
  category: string
  collection: string | null
  sizes: string | null
  stock: number
  isOriginal: boolean
  isFeatured: boolean
  isActive: boolean
  medium: string | null
  dimensions: string | null
  year: number | null
  createdAt: Date
  updatedAt: Date
}

export const INITIAL_PRODUCTS: StaticProduct[] = [
  {
    id: 'prod_1',
    slug: 'golden-hour-horizon-print',
    title: 'Golden Hour Horizon — Fine Art Print',
    description: 'An atmospheric tonal landscape capturing warm evening light over rolling coastal bluffs. Layered with soft ochres, umbers, and luminous sky. Museum-quality giclée print on 310gsm archival cotton rag.',
    price: 45,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'print',
    collection: 'landscapes',
    sizes: JSON.stringify(['5x7', '8x10', '11x14', '16x20']),
    stock: 50,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Giclée print on 310gsm archival cotton rag',
    dimensions: 'Available in 5×7, 8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'prod_2',
    slug: 'mediterranean-figs-linen-original',
    title: 'Figs & Olive Branch on Belgian Linen — Original',
    description: 'An original oil painting depicting ripe summer figs and wild olive branches bathed in northern studio light. Painted with rich textural brushwork on portrait-grade Belgian linen. Signed, varnished, and shipped with a Certificate of Authenticity.',
    price: 680,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'original',
    collection: 'still-life',
    sizes: JSON.stringify(['16x20']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on Belgian linen canvas',
    dimensions: '16 × 20 inches (Framing available)',
    year: 2026,
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-02'),
  },
  {
    id: 'prod_3',
    slug: 'nocturne-solitude-original',
    title: 'Nocturne Solitude — Original Oil',
    description: 'A contemplative evening study in deep indigo, prussian blue, and warm zinc highlights. Exploring the peaceful quiet of dusk over coastal dunes. Signed original with custom hardwood floater frame.',
    price: 1150,
    images: JSON.stringify(['/aperol.jpg', '/aperol.jpg']),
    category: 'original',
    collection: 'landscapes',
    sizes: JSON.stringify(['20x24']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on cradled wood panel',
    dimensions: '20 × 24 inches',
    year: 2026,
    createdAt: new Date('2026-01-03'),
    updatedAt: new Date('2026-01-03'),
  },
  {
    id: 'prod_4',
    slug: 'botanical-monstera-flora-print',
    title: 'Monstera & Wild Flora Print',
    description: 'A study in organic forms and cascading forest greens. Rendered with subtle brush texture and soft tonal gradients. Archival giclée reproduction on heavyweight fine art paper.',
    price: 48,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'print',
    collection: 'botanicals',
    sizes: JSON.stringify(['5x7', '8x10', '11x14']),
    stock: 50,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: 'Archival pigment print on 310gsm cotton rag',
    dimensions: 'Available in 5×7, 8×10, 11×14 inches',
    year: 2025,
    createdAt: new Date('2026-01-04'),
    updatedAt: new Date('2026-01-04'),
  },
  {
    id: 'prod_5',
    slug: 'morning-terracotta-still-life-print',
    title: 'Terracotta & Linen Study Print',
    description: 'Warm earth tones, rustic ceramics, and the delicate geometry of natural drapery. A peaceful composition designed for serene living spaces and studio walls.',
    price: 45,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'print',
    collection: 'still-life',
    sizes: JSON.stringify(['5x7', '8x10', '11x14']),
    stock: 50,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: 'Giclée print on archival matte paper',
    dimensions: 'Available in 5×7, 8×10, 11×14 inches',
    year: 2025,
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'prod_6',
    slug: 'catskill-mist-original',
    title: 'Catskill Morning Mist — Original Oil',
    description: 'A large landscape capturing dawn breaking through mountain mist. Expressive impasto palette knife work meets delicate atmospheric glazes. One-of-a-kind original.',
    price: 1400,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'original',
    collection: 'landscapes',
    sizes: JSON.stringify(['24x30']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on heavy Belgian linen',
    dimensions: '24 × 30 inches',
    year: 2026,
    createdAt: new Date('2026-01-06'),
    updatedAt: new Date('2026-01-06'),
  },
  {
    id: 'prod_7',
    slug: 'coastal-solitude-print',
    title: 'Coastal Solitude Print',
    description: 'Subtle ocean blues and chalky shorelines rendered with minimalist elegance. An evocative print that brings calm and natural openness to modern interiors.',
    price: 45,
    images: JSON.stringify(['/aperol.jpg', '/aperol.jpg']),
    category: 'print',
    collection: 'landscapes',
    sizes: JSON.stringify(['8x10', '11x14', '16x20']),
    stock: 45,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: 'Museum giclée print on smooth rag',
    dimensions: '8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-07'),
    updatedAt: new Date('2026-01-07'),
  },
]
