export interface StaticProduct {
  id: string
  slug: string
  title: string
  description: string
  price: number
  images: string
  category: string
  collection: string | null
  sizes: string | null
  stock: number
  isOriginal: boolean
  isFeatured: boolean
  isActive: boolean
  medium: string | null
  dimensions: string | null
  year: number | null
  createdAt: Date
  updatedAt: Date
}

export const INITIAL_PRODUCTS: StaticProduct[] = [
  {
    id: 'prod_1',
    slug: 'orange-slices-still-life-print',
    title: 'Orange Slices & Aperol Study — Fine Art Print',
    description: 'An evocative still life exploring sunlight filtering through translucent citrus slices and an iced aperitif. Rendered with luminous glazes and textured linen brushwork. Printed on 310gsm museum-grade cotton rag.',
    price: 45,
    images: JSON.stringify(['/aperol.jpg', '/aperol.jpg']),
    category: 'print',
    collection: 'food-drink',
    sizes: JSON.stringify(['5x7', '8x10', '11x14', '16x20']),
    stock: 50,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Archival pigment print on 310gsm heavy cotton rag',
    dimensions: '5×7, 8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'prod_2',
    slug: 'figs-and-berries-belgian-linen-original',
    title: 'Summer Figs & Wild Berries on Belgian Linen — Original',
    description: 'An original oil painting depicting ripe Kadota figs, fresh berries, and morning studio light on textured Belgian linen. Signed, varnished, and shipped in custom archival crating with a Certificate of Authenticity.',
    price: 680,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'original',
    collection: 'still-life',
    sizes: JSON.stringify(['16x20']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on primed Belgian linen canvas',
    dimensions: '16 × 20 inches (Custom floater frame optional)',
    year: 2026,
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-02'),
  },
  {
    id: 'prod_3',
    slug: 'oysters-and-martini-table-print',
    title: 'Oysters & Dirty Martini Table Print',
    description: 'A celebration of conviviality — fresh briny oysters on crushed ice paired with a classic dry olive martini. A collectors favorite for dining spaces, bars, and kitchen vignettes.',
    price: 48,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'print',
    collection: 'food-drink',
    sizes: JSON.stringify(['5x7', '8x10', '11x14', '16x20']),
    stock: 45,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Museum giclée print on 310gsm archival paper',
    dimensions: '5×7, 8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-03'),
    updatedAt: new Date('2026-01-03'),
  },
  {
    id: 'prod_4',
    slug: 'wild-blueberries-draped-linen-print',
    title: 'Wild Blueberries & Draped Linen Study Print',
    description: 'Rich prussian blues and buttery folds of natural linen. Captured in soft northern window light with expressive, tactile impasto brushwork.',
    price: 45,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'print',
    collection: 'still-life',
    sizes: JSON.stringify(['5x7', '8x10', '11x14']),
    stock: 50,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Giclée reproduction on 310gsm velvet rag',
    dimensions: '5×7, 8×10, 11×14 inches',
    year: 2025,
    createdAt: new Date('2026-01-04'),
    updatedAt: new Date('2026-01-04'),
  },
  {
    id: 'prod_5',
    slug: 'assorted-fruit-peaches-original',
    title: 'Peaches & Summer Table Study — Original Oil',
    description: 'A large, radiant oil painting featuring ripe yellow peaches and rustic glazed ceramics bathed in afternoon warmth. Painted with rich impasto and luminous layered glazes.',
    price: 1400,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'original',
    collection: 'still-life',
    sizes: JSON.stringify(['24x30']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on heavy Belgian portrait linen',
    dimensions: '24 × 30 inches',
    year: 2026,
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'prod_6',
    slug: 'citrus-spritz-terrace-print',
    title: 'Citrus Spritz on Sunlit Terrace Print',
    description: 'Vibrant blood oranges, sparkling glassware, and warm terracotta tiles. Brings the lively, joyful warmth of an Italian afternoon to your walls.',
    price: 45,
    images: JSON.stringify(['/aperol.jpg', '/aperol.jpg']),
    category: 'print',
    collection: 'food-drink',
    sizes: JSON.stringify(['8x10', '11x14', '16x20']),
    stock: 50,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Archival fine art print on 310gsm cotton paper',
    dimensions: '8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-06'),
    updatedAt: new Date('2026-01-06'),
  },
  {
    id: 'prod_7',
    slug: 'galette-and-cherries-original',
    title: 'Rustic Berry Galette & Cherries — Original Oil',
    description: 'Golden flaky pastry, glistening summer blackberries, and dark sweet cherries. A quiet, intimate celebration of simple kitchen craft and domestic beauty.',
    price: 950,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'original',
    collection: 'food-drink',
    sizes: JSON.stringify(['12x16']),
    stock: 1,
    isOriginal: true,
    isFeatured: false,
    isActive: true,
    medium: 'Oil on cradled birch panel',
    dimensions: '12 × 16 inches',
    year: 2026,
    createdAt: new Date('2026-01-07'),
    updatedAt: new Date('2026-01-07'),
  },
]
