export interface StaticProduct {
  id: string
  slug: string
  title: string
  description: string
  price: number
  originalPrice?: number
  images: string
  category: string
  collection: string | null
  sizes: string | null
  stock: number
  isOriginal: boolean
  isFeatured: boolean
  isActive: boolean
  medium: string | null
  dimensions: string | null
  year: number | null
  createdAt: Date
  updatedAt: Date
}

export const INITIAL_PRODUCTS: StaticProduct[] = [
  // ── Bestselling Prints ───────────────────────────────────────────────────
  {
    id: 'prod_1',
    slug: 'orange-slices-print',
    title: 'Orange Slices Print',
    description: 'An iconic still life capturing sunlight illuminating translucent citrus slices. Archival pigment print on 310gsm museum-grade cotton rag.',
    price: 45,
    images: JSON.stringify(['/aperol.jpg', '/aperol.jpg']),
    category: 'print',
    collection: 'food-drink',
    sizes: JSON.stringify(['5x7', '8x10', '11x14', '16x20']),
    stock: 50,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Archival pigment print on 310gsm cotton rag',
    dimensions: 'Available in 5×7, 8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-01'),
  },
  {
    id: 'prod_2',
    slug: 'manhattan-print',
    title: 'Manhattan Print',
    description: 'A glowing coupe glass with maraschino cherries and rich amber cocktail tones against a deep crimson backdrop.',
    price: 45,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'print',
    collection: 'food-drink',
    sizes: JSON.stringify(['5x7', '8x10', '11x14', '16x20']),
    stock: 50,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Archival pigment print on 310gsm cotton rag',
    dimensions: 'Available in 5×7, 8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-02'),
    updatedAt: new Date('2026-01-02'),
  },
  {
    id: 'prod_3',
    slug: 'jewels-drenched-print',
    title: 'Jewels, Drenched Print',
    description: 'Ripe pomegranates, figs, and honeyed fruit glowing in deep warm chiaroscuro light.',
    price: 45,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'print',
    collection: 'still-life',
    sizes: JSON.stringify(['5x7', '8x10', '11x14', '16x20']),
    stock: 50,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Giclée reproduction on 310gsm velvet rag',
    dimensions: 'Available in 5×7, 8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-03'),
    updatedAt: new Date('2026-01-03'),
  },
  {
    id: 'prod_4',
    slug: 'oysters-and-martini-table-print',
    title: 'Oysters and Martini Table Print',
    description: 'Fresh oysters on crushed ice paired with a classic dirty martini and lemon. A perennial collector favorite.',
    price: 45,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'print',
    collection: 'food-drink',
    sizes: JSON.stringify(['5x7', '8x10', '11x14', '16x20']),
    stock: 45,
    isOriginal: false,
    isFeatured: true,
    isActive: true,
    medium: 'Museum giclée print on archival paper',
    dimensions: 'Available in 5×7, 8×10, 11×14, 16×20 inches',
    year: 2025,
    createdAt: new Date('2026-01-04'),
    updatedAt: new Date('2026-01-04'),
  },

  // ── Originals (Become a Collector) ─────────────────────────────────────────
  {
    id: 'prod_5',
    slug: 'galette-8x10-inch-original',
    title: 'Galette, 8x10 Inch Original',
    description: 'An intimate original oil study of sliced tomatoes, zucchini, and pastry crust on Belgian linen.',
    price: 500,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'original',
    collection: 'still-life',
    sizes: JSON.stringify(['8x10']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on Belgian linen canvas',
    dimensions: '8 × 10 inches',
    year: 2026,
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'prod_6',
    slug: 'fish-market-march-2026-24x48-inch-original',
    title: 'Fish Market (March 2026), 24x48 Inch Original',
    description: 'A grand-scale statement original oil painting featuring luminous blue mackerel and textural palette knife strokes on heavy linen.',
    price: 2000,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'original',
    collection: 'still-life',
    sizes: JSON.stringify(['24x48']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on heavy Belgian linen',
    dimensions: '24 × 48 inches',
    year: 2026,
    createdAt: new Date('2026-01-06'),
    updatedAt: new Date('2026-01-06'),
  },
  {
    id: 'prod_7',
    slug: 'assorted-fruit-20x24-inch-original',
    title: 'Assorted Fruit, 20x24 Inch Original',
    description: 'Vibrant still life of summer apples, plums, blackberries, and warm drapery. Marked down from gallery catalog price.',
    price: 900,
    originalPrice: 1200,
    images: JSON.stringify(['/aperol.jpg', '/aperol.jpg']),
    category: 'original',
    collection: 'still-life',
    sizes: JSON.stringify(['20x24']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on cradled wood panel',
    dimensions: '20 × 24 inches',
    year: 2026,
    createdAt: new Date('2026-01-07'),
    updatedAt: new Date('2026-01-07'),
  },
  {
    id: 'prod_8',
    slug: 'pomegranate-and-cherries-10x10-inch-original',
    title: 'Pomegranate and Cherries, 10x10 Inch Original',
    description: 'Luminous red jewel-toned study of split pomegranates and sweet cherries in northern studio light.',
    price: 400,
    originalPrice: 525,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'original',
    collection: 'still-life',
    sizes: JSON.stringify(['10x10']),
    stock: 1,
    isOriginal: true,
    isFeatured: true,
    isActive: true,
    medium: 'Oil on linen board',
    dimensions: '10 × 10 inches',
    year: 2026,
    createdAt: new Date('2026-01-08'),
    updatedAt: new Date('2026-01-08'),
  },

  // ── 200+ Mini Prints Collection ──────────────────────────────────────────
  {
    id: 'prod_9',
    slug: 'lemon-sprig-mini-print',
    title: 'Lemon Sprig Mini Print',
    description: 'Petite 4x6 inch vibrant art print on archival heavy card stock. Perfect for mini frame gallery walls.',
    price: 18,
    images: JSON.stringify(['/aperol.jpg', '/aperol.jpg']),
    category: 'print',
    collection: 'mini-prints',
    sizes: JSON.stringify(['4x6']),
    stock: 100,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: 'Heavyweight matte archival cardstock',
    dimensions: '4 × 6 inches',
    year: 2026,
    createdAt: new Date('2026-01-09'),
    updatedAt: new Date('2026-01-09'),
  },
  {
    id: 'prod_10',
    slug: 'espresso-martini-mini-print',
    title: 'Espresso Martini Mini Print',
    description: 'Rich foam crema and dark coffee liqueur in a mini desktop collector print format.',
    price: 18,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'print',
    collection: 'mini-prints',
    sizes: JSON.stringify(['4x6']),
    stock: 85,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: 'Heavyweight matte archival cardstock',
    dimensions: '4 × 6 inches',
    year: 2026,
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'prod_11',
    slug: 'wild-fig-mini-print',
    title: 'Wild Fig & Honey Mini Print',
    description: 'Petite luscious study of ripe figs dripping with golden wildflower honey.',
    price: 18,
    images: JSON.stringify(['/berries.jpg', '/berries.jpg']),
    category: 'print',
    collection: 'mini-prints',
    sizes: JSON.stringify(['4x6']),
    stock: 90,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: 'Heavyweight matte archival cardstock',
    dimensions: '4 × 6 inches',
    year: 2026,
    createdAt: new Date('2026-01-11'),
    updatedAt: new Date('2026-01-11'),
  },

  // ── Stickers ─────────────────────────────────────────────────────────────
  {
    id: 'prod_12',
    slug: 'martini-olive-vinyl-sticker',
    title: 'Martini & Olive Die-Cut Sticker',
    description: 'Heavyweight waterproof holographic vinyl sticker featuring original oil artwork illustration.',
    price: 6,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'sticker',
    collection: 'stickers',
    sizes: JSON.stringify(['3x3']),
    stock: 200,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: 'UV-resistant weatherproof vinyl',
    dimensions: '3 × 3 inches',
    year: 2026,
    createdAt: new Date('2026-01-12'),
    updatedAt: new Date('2026-01-12'),
  },
  {
    id: 'prod_13',
    slug: 'sardines-tin-vinyl-sticker',
    title: 'Sardines Tin Vinyl Sticker',
    description: 'Durable scratch-resistant die-cut vinyl sticker of oil-painted blue mackerel and sardines.',
    price: 6,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'sticker',
    collection: 'stickers',
    sizes: JSON.stringify(['3.5x2.5']),
    stock: 200,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: 'UV-resistant weatherproof vinyl',
    dimensions: '3.5 × 2.5 inches',
    year: 2026,
    createdAt: new Date('2026-01-13'),
    updatedAt: new Date('2026-01-13'),
  },

  // ── Apparel & Homewares ──────────────────────────────────────────────────
  {
    id: 'prod_14',
    slug: 'oyster-linen-tea-towel',
    title: 'Oyster Bar 100% Linen Tea Towel',
    description: 'Custom screen-printed 100% French flax linen kitchen towel featuring the iconic oyster and martini artwork.',
    price: 34,
    images: JSON.stringify(['/hero.jpg', '/hero.jpg']),
    category: 'homeware',
    collection: 'homewares',
    sizes: JSON.stringify(['Standard']),
    stock: 40,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: '100% French flax linen',
    dimensions: '18 × 28 inches',
    year: 2026,
    createdAt: new Date('2026-01-14'),
    updatedAt: new Date('2026-01-14'),
  },
  {
    id: 'prod_15',
    slug: 'citrus-tote-bag',
    title: 'Citrus Slices Heavy Canvas Tote',
    description: 'Sturdy 12oz organic cotton canvas market tote with reinforced shoulder straps and interior pocket.',
    price: 38,
    images: JSON.stringify(['/aperol.jpg', '/aperol.jpg']),
    category: 'homeware',
    collection: 'homewares',
    sizes: JSON.stringify(['One Size']),
    stock: 35,
    isOriginal: false,
    isFeatured: false,
    isActive: true,
    medium: '12oz organic cotton canvas',
    dimensions: '16 × 15 × 4 inches',
    year: 2026,
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-15'),
  },
]
